version: '3'
services:
  web:
    image: "docker-node-mongo"
    build: .
    command: "node server.js"
    ports:
      - "8080:5000"
    links:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
# image: container name
# links: link the web service to mongo service